---
# tasks file for centos-bootstrap

- name: Ensure deltarpm installed (before updating CentOS packages)
  yum: name=deltarpm state=latest

- name: Update CentOS packages
  yum: name=* state=latest update_cache=yes

- name: Ensure EPEL installed
  yum: name=epel-release state=latest

- name: Ensure basic sysadmin tools installed
  yum: name={{ item }} state=latest
  with_items: sysadmin_tools

- name: Set the default text editor for {{ ansible_ssh_user }} to {{ text_editor }}
  # Some VPS providers ship Centos 7 with Nano as default, some with Vim
  lineinfile:
    dest: "/home/{{ ansible_ssh_user }}/.bash_profile"
    regexp: "^export EDITOR="
    line: "export EDITOR={{ text_editor }}"

- name: Set the default text editor for root to {{ text_editor }}
  # Some VPS providers ship Centos 7 with Nano as default, some with Vim
  lineinfile:
    dest: "/root/.bash_profile"
    regexp: "^export EDITOR="
    line: "export EDITOR={{ text_editor }}"

- name: Start cron(ie)
  service: name=crond state=started enabled=yes
  tags: cronie

- name: Start synchronizing the system Clock
  service: name=ntpd state=started enabled=yes
  tags: ntpd

- name: Customizing SELinux
  lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=permissive

- name: sshd configuration file update
  template: src=./files/sshd_config.j2
    dest=/etc/ssh/sshd_config
    backup=yes
    owner=0 group=0 mode=0644
  notify:
  - restart sshd

#- name: Open port in firewall
#  firewalld: port=22/tcp permanent=true state=enabled immediate=true
#  when: not ( security_firewall is defined and not security_firewall )

- name: Rsyslog-Config
  lineinfile: dest=/etc/rsyslog.conf regexp="^#*.* @@remote-host:514" line="*.* @192.168.24.2:514"

- name: copy myglobalenv.sh with Special Modifications
  copy: src=./files/myglobalenv.sh dest=/etc/profile.d

