---

- name: sshd configuration file update
  template: src=./files/sshd_config.j2
    dest=/etc/ssh/sshd_config
    backup=yes
    owner=0 group=0 mode=0644
  notify:
  - restart sshd

- firewalld: service=ssh permanent=true state=enabled
